[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.14.0",
    "fastapi>=0.141.1",
    "fire>=0.7.1",
    "flake8>=7.3.0",
    "more-itertools>=11.1.0",
    "mypy>=2.3.0",
    "numpy>=2.5.1",
    "pydantic>=2.13.4",
    "pytest>=9.1.1",
    "rank-bm25>=0.2.2",
    "sentence-transformers>=5.6.1",
    "torch>=2.13.0",
    "tqdm>=4.69.1",
    "transformers>=5.14.1",
    "uvicorn>=0.52.0",
]
[[tool.mypy.overrides]]
module = [
    "tqdm",
    "rank_bm25",
    "fire",
    "fastapi",
    "uvicorn",
    "sentence_transformers"
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "src.api"
disallow_untyped_decorators = false
